---
# v314
# ANSIBLE_COLLECTIONS_PATH=$PWD ansible-playbook -e @inventory_quay314_registry01.yaml create_quay_first_user.yaml
# ANSIBLE_COLLECTIONS_PATH=$PWD ansible-playbook -e @inventory_quay314_registry02.yaml create_quay_first_user.yaml

# v317
# ANSIBLE_COLLECTIONS_PATH=$PWD ansible-playbook -e @inventory_quay317_registry01.yaml create_quay_first_user.yaml
# ANSIBLE_COLLECTIONS_PATH=$PWD ansible-playbook -e @inventory_quay317_registry02.yaml create_quay_first_user.yaml
- name: Bootstrapping a fresh Quay Container Registry installation
  hosts: all
  connection: "local"

  tasks:
    - name: Ensure the initial user exists
      infra.quay_configuration.quay_first_user:
        username: quayadmin
        email: quayadmin@lab.localdomain
        password: password
        create_token: true
        quay_host: https://{{ quay_fqdn }}:{{ https_port }}
        validate_certs: false
      register: result

    # The token is valid for 2 hours and 30 minutes
    - name: Display the generated OAuth access token
      debug:
        msg: "Access token: {{ result['access_token'] }}"
...
