---
# ANSIBLE_COLLECTIONS_PATH=$PWD ansible-playbook -e @inventory_quay_mirror.yaml quay_site_mirror.yaml 
- name: "Ensure registry configurations"
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  module_defaults:
    group/infra.quay_configuration.quay:
      quay_host: "{{ 'https://' + quay_hostname }}"
      quay_token: "{{ quay_org_app_token }}"
      validate_certs: false
    ansible.builtin.uri:
      validate_certs: false
  tasks:
    - name: "Query primary Quay API to gather organization repositories"
      ansible.builtin.shell: |
        #!/usr/bin/env bash

        TOKEN="{{ source_quay_token }}"
        NAMESPACE="{{ source_quay_organization }}"
        BASE_URL="{{ 'https://' + source_quay_hostname + '/api/v1' }}"

        NEXT_PAGE=""
        while true; do
          if [[ -n "$NEXT_PAGE" ]]; then
            URL="$BASE_URL/repository?namespace=$NAMESPACE&next_page=$NEXT_PAGE"
          else
            URL="$BASE_URL/repository?namespace=$NAMESPACE"
          fi

          RESPONSE=$(curl -k -s -X GET -H "Accept: application/json" -H "Authorization: Bearer $TOKEN" "$URL")

          REPOS=$(echo "$RESPONSE" | jq -r '.repositories[]?.name')

          echo "$REPOS"

          NEXT_PAGE=$(echo "$RESPONSE" | jq -r '.next_page')

          if [[ "$NEXT_PAGE" == "null" || -z "$NEXT_PAGE" ]]; then
            break
          fi

        done

      register: primary_quay_organization_repos_list

    - ansible.builtin.debug:
        var: primary_quay_organization_repos_list.stdout_lines
    
    - name: "Set repolist"
      ansible.builtin.set_fact:
        repolist: "{{ primary_quay_organization_repos_list.stdout_lines }}"
    
    - name: "Ensure repositories exists in the organization"
      infra.quay_configuration.quay_repository:
        name: "{{ organization + '/' + item }}"
        visibility: "private"
        state: "present"
      loop: "{{ repolist }}"

    - name: "Ensure mirroring is set for the existing repos"
      infra.quay_configuration.quay_repository_mirror:
        name: "{{ organization + '/' + item }}"
        external_reference: "{{ source_quay_hostname + '/' + source_quay_organization + '/' + item }}"
        robot_username: "{{ robot_account }}"
        is_enabled: true
        force_sync: false
        sync_interval: 300
        verify_tls: false
        # sync_start_date: "2026-05-07T16:50:00Z" # date -I'ns' -u
        image_tags:
          - '*'
        external_registry_username: "{{ source_quay_username }}"
        external_registry_password: "{{ source_quay_password }}"
        skopeo_timeout: "{{ skopeo_tmout | default(omit) }}"
      loop: "{{ repolist }}"
...
