---
- name: "Create CA and Certs"
  ansible.builtin.import_playbook: "create_ca_certs.yaml"

- name: "Deploy Red Hat Quay Enterprise (PoC)"
  ansible.builtin.import_playbook: "create_quay.yaml"

- name: "Bootstrapping a fresh Quay Container Registry installation"
  ansible.builtin.import_playbook: "create_quay_first_user.yaml"

- name: "Seed Quay Container Registry installation"
  ansible.builtin.import_playbook: "quay_seed.yaml"

- name: "Ensure registry configurations"
  ansible.builtin.import_playbook: "quay_site_mirror.yaml"
...
