---
- name: "Compliance Sync - Org A to Org B"
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    _source_quay_hostname: "{{ source_quay_hostname | default(lookup('ansible.builtin.env', 'SOURCE_QUAY_HOSTNAME')) | mandatory }}"
    _source_quay_token: "{{ source_quay_token | default(lookup('ansible.builtin.env', 'SOURCE_QUAY_TOKEN')) | mandatory }}"
    _source_quay_validate_certs: "{{ source_quay_validate_certs | default(lookup('ansible.builtin.env', 'SOURCE_QUAY_VALIDATE_CERTS')) | default('false') }}"
    _source_quay_organization: "{{ source_quay_organization | default(lookup('ansible.builtin.env', 'SOURCE_QUAY_ORGANIZATION')) | mandatory }}"
    _source_quay_username: "{{ source_quay_username | default(lookup('ansible.builtin.env', 'SOURCE_QUAY_USERNAME')) | mandatory }}"
    _source_quay_password: "{{ source_quay_password | default(lookup('ansible.builtin.env', 'SOURCE_QUAY_PASSWORD')) | mandatory }}"
    _destination_quay_hostname: "{{ destination_quay_hostname | default(lookup('ansible.builtin.env', 'DESTINATION_QUAY_HOSTNAME')) | mandatory }}"
    _destination_quay_token: "{{ destination_quay_token | default(lookup('ansible.builtin.env', 'DESTINATION_QUAY_TOKEN')) | mandatory }}"
    _destination_validate_certs: "{{ destination_quay_validate_certs | default(lookup('ansible.builtin.env', 'DESTINATION_QUAY_VALIDATE_CERTS')) | default('false') | bool }}"
    _destination_quay_organization: "{{ destination_quay_organization | default(lookup('ansible.builtin.env', 'DESTINATION_QUAY_ORGANIZATION')) | mandatory }}"
    _destination_quay_username: "{{ destination_quay_username | default(lookup('ansible.builtin.env', 'DESTINATION_QUAY_USENAME')) | mandatory }}"
    _skopeo_tmout: "{{ skopeo_tmout | default('300') }}"
  tasks:
    - name: "Query Quay(SOURCE) API to gather organization repositories"
      ansible.builtin.shell: |
        #!/usr/bin/env bash

        TOKEN="{{ _source_quay_token }}"
        NAMESPACE="{{ _source_quay_organization }}"
        BASE_URL="{{ 'https://' + _source_quay_hostname + '/api/v1' }}"

        NEXT_PAGE=""
        while true; do
          if [[ -n "$NEXT_PAGE" ]]; then
            URL="$BASE_URL/repository?namespace=$NAMESPACE&next_page=$NEXT_PAGE"
          else
            URL="$BASE_URL/repository?namespace=$NAMESPACE"
          fi

          RESPONSE=$(curl -k -s -X GET -H "Accept: application/json" -H "Authorization: Bearer $TOKEN" "$URL")

          REPOS=$(echo "$RESPONSE" | jq -r '.repositories[]?.name')

          echo "$REPOS"

          NEXT_PAGE=$(echo "$RESPONSE" | jq -r '.next_page')

          if [[ "$NEXT_PAGE" == "null" || -z "$NEXT_PAGE" ]]; then
            break
          fi

        done

      register: "source_quay_organization_repos_list"

    - name: "Set source repolist"
      ansible.builtin.set_fact:
        repolist_source: "{{ source_quay_organization_repos_list.stdout_lines }}"

    - name: "Query Quay(destination) API to gather organization repositories"
      ansible.builtin.shell: |
        #!/usr/bin/env bash

        TOKEN="{{ _destination_quay_token }}"
        NAMESPACE="{{ _destination_quay_organization }}"
        BASE_URL="{{ 'https://' + _destination_quay_hostname + '/api/v1' }}"

        NEXT_PAGE=""
        while true; do
          if [[ -n "$NEXT_PAGE" ]]; then
            URL="$BASE_URL/repository?namespace=$NAMESPACE&next_page=$NEXT_PAGE"
          else
            URL="$BASE_URL/repository?namespace=$NAMESPACE"
          fi

          RESPONSE=$(curl -k -s -X GET -H "Accept: application/json" -H "Authorization: Bearer $TOKEN" "$URL")

          REPOS=$(echo "$RESPONSE" | jq -r '.repositories[]?.name')

          echo "$REPOS"

          NEXT_PAGE=$(echo "$RESPONSE" | jq -r '.next_page')

          if [[ "$NEXT_PAGE" == "null" || -z "$NEXT_PAGE" ]]; then
            break
          fi

        done

      register: "destionation_quay_organization_repos_list"

    - name: "Set destination repolist"
      ansible.builtin.set_fact:
        repolist_destination: "{{ destionation_quay_organization_repos_list.stdout_lines }}"

    - name: "DEBUG - Display repository list for source and destination"
      ansible.builtin.debug:
        msg: 
          - "source_repos: {{ repolist_source }}"
          - "destionation_repos: {{ repolist_destination }}"

    # - ansible.builtin.pause:

    - name: "GUARDRAIL - Abort if Org A returns empty"
      assert:
        that:
          - repolist_source is defined
          - repolist_source | length > 0
        fail_msg: "CAUTION: Org A returned 0 repositories at source. Aborting entire execution."
      when: repolist_destination | default([]) | length > 0

    - name: "Identify orphan and common repositories"
      set_fact:
        repos_to_delete: "{{ repolist_destination | difference(repolist_source) }}"
        common_repos: "{{ repolist_destination | intersect(repolist_source) }}"

    - name: "DEBUG - Display repositories to be removed and kept"
      ansible.builtin.debug:
        msg: 
          - "repos_to_delete: {{ repos_to_delete }}"
          - "common_repos: {{ common_repos }}"

    # - ansible.builtin.pause:

    - name: "Remove entire repositories in B that no longer exist in A"
      infra.quay_configuration.quay_repository:
        quay_host: "{{ _destination_quay_hostname }}"
        quay_token: "{{ _destination_quay_token }}"
        name: "{{ _destination_quay_organization }}/{{ item }}"
        state: "absent"
        verify_ssl: false
      loop: "{{ repos_to_delete }}"
      when: repos_to_delete | length > 0
      # throttle: 1
...
